config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'leader_boards#index'

  resources :games

  resources :members
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# frozen_string_literal: true

# Game model
class Game < ApplicationRecord
  # for slug
  extend FriendlyId
  friendly_id :title, use: :slugged

  # Relationships
  has_many :participants, dependent: :destroy

  # nested attributes for add participants player
  accepts_nested_attributes_for :participants

  def change_player_status
    game_participants = participants.order(score: :desc).ids
    if game_participants.count <= 1
      update(status: 'winner')
    else
      Participant.where(id: game_participants.shift).update(status: 'winner')
      Participant.where(id: game_participants).update(status: 'loser')
    end
  end
end

app/models/member.rb
# frozen_string_literal: true

# Member model
class Member < ApplicationRecord
  # for slug
  extend FriendlyId
  friendly_id :full_name, use: :slugged

  # Relationships
  has_many :participants, dependent: :destroy

  # Validations
  validates :full_name, :email, presence: true
  validates :mobile_number, presence: true, numericality: true, length: { minimum: 10, maximum: 15 }

  # Participants counts
  def number_of_games
    participants.count
  end

  # this method return custom hash with rank details
  def rank_details
    participant = participants.order(score: :desc).first
    return nil unless participant.present?

    game = participant.game
    another_palyer = game.participants.where.not(member_id: participant.member_id).last&.member&.full_name
    { highest_score: participant.score, game_name: game.title, game_time: game.created_at, another_player: another_palyer }
  end
end

app/models/participant.rb
# frozen_string_literal: true

# Participant model
class Participant < ApplicationRecord
  # enum
  enum status: %i[winner loser]

  # Relationships
  belongs_to :member
  belongs_to :game

  # Validations
  validates :game_id, uniqueness: { scope: :member_id }
  validates :score, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
# frozen_string_literal: true

# games controller
class GamesController < ApplicationController
  before_action :fetch_game, only: :show

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
    2.times { @game.participants.build }
  end

  def create
    @game = Game.new(game_params)
    if @game.participants[0][:member_id].eql?(@game.participants[1][:member_id])
      redirect_to :new, notice: 'Same member not allow.'
    else
      if @game.save
        @game.change_player_status
        redirect_to games_path
      else
        render :new
      end
    end
  end

  def show; end

  private

  # fetch game data
  def fetch_game
    @game = Game.friendly.find(params[:id])
  end

  # strong params permit
  def game_params
    params.require(:game).permit(:title, :description, participants_attributes: %i[member_id score])
  end
end

app/controllers/leader_boards_controller.rb
# frozen_string_literal: true

# leader board controller
class LeaderBoardsController < ApplicationController
  def index
    participant_players_ids = Member.joins(:participants).group('members.id').having('count(participants.id) >= 10')
    @top_score_members = Member.where(id: participant_players_ids).includes(:participants).order('participants.score desc').limit(10)
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

# member controller
class MembersController < ApplicationController
  before_action :fetch_member, only: %i[show edit update destroy]

  def index
    @members = Member.all.order(:full_name)
  end

  def show
    @rank_details = @member.rank_details
  end

  def new
    @member = Member.new
  end

  def edit; end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to members_path
    else
      render :new
    end
  end

  def update
    if @member.update(member_params)
      redirect_to members_path
    else
      render :edit
    end
  end

  def destroy
    @member.destroy
    redirect_to members_path
  end

  private

  def fetch_member
    @member = Member.friendly.find(params[:id])
  end

  def member_params
    params.require(:member).permit(:full_name, :email, :mobile_number, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/leader_boards_helper.rb
module LeaderBoardsHelper
end

app/helpers/members_helper.rb
# frozen_string_literal: true

# Member helper
module MembersHelper
  def avrage_score(participants)
    participants.average(:score).round(2)
  end

  def win_games_count(participants)
    participants.where(status: 'winner').count
  end

  def los_games_count(participants)
    participants.where(status: 'loser').count
  end
end

app/views/games/_form.html.erb
<%= form_for @game do |form| %>
    <% if @game.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@game.errors.count, "error") %> prohibited this @game from being saved:</h2>

        <ul>
        <% @game.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>
    <div class="form-group">
        <%= form.label :title, for: "title" %>
        <%= form.text_field :title, type: "title", class: "form-control", required: true %>
    </div>

    <div class="form-group">
        <%= form.label :description, for: "description" %>
        <%= form.text_area :description, type: "description", class: "form-control", rows: "3" %>
    </div>
    
    <b>Participant Players:</b>
    <ul>
      <%= form.fields_for :participants do |participants_form| %>
        <div class="form-group">
            <%= participants_form.label :name, for: "name" %>
            <%= participants_form.select :member_id, options_for_select(Member.all.collect {|c| [ c.full_name, c.id ] }), {}, { class: 'form-control', required: true} %>
        <div>
        <div class="form-group">
            <%= participants_form.label :score, for: "score" %>
            <%= participants_form.number_field :score, class: "form-control", required: true %>
        </div>
      <% end %>
    </ul>
    <div class="form-group">
        <%= form.button :submit, class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/games/index.html.erb
<%= content_for :header do %>
    <h1>List of Games</h1>
  <% end %>
  
  <%= link_to 'Create Game', new_game_path %>
  <hr>
  
  <% if @games.blank? %>
    <p>Do not have any games.</p>
  <% else %>
    <table>
      <thead>
        <tr>
          <td>Name</td>
          <td>Description</td>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= link_to "#{game.title}", game_path(id: game.id) %></td>
            <td><%= game.description %></td>
            <td><%#= link_to 'Edit', edit_games_path(game) %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  
  <hr>

app/views/games/new.html.erb
<%= content_for :header do %>
    <h1>New Game</h1>
<% end %>
<%= render partial: 'form' %>
  
<hr>

app/views/games/show.html.erb
<h1>Game Details</h1>
<hr>
<table>
  <tr>
    <td>
      <strong>Title : </strong>
    </td>
    <td>
      <%= @game.title %>
    </td>
  </tr>
</table>
<table>
  <tr>
    <td><b>Name</b></td>
    <td><b>Score</b></td>
    <td><b>Status</b></td>
  </tr>
  <% @game.participants.each do |participant| %>
    <tr>
      <td>
        <%= participant.member.full_name %>
      </td>
      <td>
        <%= participant.score %>
      </td>
      <td>
        <%= participant.status %>
      </td>
    </tr>
  <% end %>
</table> 
<hr>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'LeaderBoards', root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to 'Members', members_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Games', games_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScrableClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='container'>
    <%= render partial: 'layouts/header' %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/leader_boards/index.html.erb
<% if @top_score_members.blank? %>
  <p>Does not have any users having more than 10 matches</p>
<% else %>
  <table>
    <tr>
      <td><strong>Rank</strong></td>
      <td><strong>Member Name</strong></td>
      <td><strong>Avg Score</strong></td>
    </tr>
    <% @top_score_members.each_with_index do |member, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= member.full_name %></td>
        <td><%= avrage_score(member.participants) %></td>
      </tr>
    <% end %>
  </table>
<% end %>
<hr>

app/views/members/_form.html.erb
<%= content_for :header do %>
    <h1>New Member</h1>
<% end %>
  
<%= form_for @member do |form| %>
    <% if @member.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@member.errors.count, "error") %> prohibited this @member from being saved:</h2>

        <ul>
        <% @member.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>
    <div class="form-group">
        <%= form.label :full_name, for: "full_name" %>
        <%= form.text_field :full_name, type: "full_name", class: "form-control" %>
    </div>

    <div class="form-group">
        <%= form.label :email, for: "email" %>
        <%= form.text_field :email, type: "email", class: "form-control", required: true %>
    </div>

    <div class="form-group">
        <%= form.label :mobile_number, for: "mobile_number" %>
        <%= form.text_field :mobile_number, type: "mobile_number", class: "form-control", required: true %>
    </div>

    <div class="form-group">
        <%= form.label :address, for: "address" %>
        <%= form.text_area :address, type: "address", class: "form-control", rows: "3" %>
    </div>
    
    <div class="form-group">
        <%= form.button :submit, class: 'btn btn-primary' %>
    </div>
<% end %>
  
<hr>

app/views/members/edit.html.erb
<h1>Edit Member</h1><hr>
<%= render partial: 'form', member: @member %>

<hr>

app/views/members/index.html.erb
<h1>Member List</h1><hr>
  
  <%= link_to 'Create Member', new_member_path %>
  <hr>
  
  <% if @members.blank? %>
    <p>Do not have any members.</p>
  <% else %>
    <table>
      <thead>
        <tr>
          <td>Name</td>
          <td>Email</td>
          <td>Contact</td>
          <td>Address</td>
          <td>Action</td>
        </tr>
      </thead>
      <tbody>
        <% @members.each do |member| %>
          <tr>
            <td><%= link_to member.full_name, member_path(member) %></td>
            <td><%= member.email %></td>
            <td><%= member.mobile_number %></td>
            <td><%= member.address %></td>
            <td><%= link_to 'Edit', edit_member_path(member) %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <hr>

app/views/members/new.html.erb
<h1>New Member</h1><hr>
<%= render partial: 'form' %>
  
<hr>

app/views/members/show.html.erb
<h1>Member Details</h1><hr>
<table>
  <tr>
    <td>
      <strong>Full Name : </strong>
    </td>
    <td>
      <%= @member.full_name %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Email : </strong>
    </td>
    <td>
      <%= @member.email %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Mobile Number : </strong>
    </td>
    <td>
      <%= @member.mobile_number %>
    </td>
  </tr>
  <tr>
    <td>
      <strong>Address : </strong>
    </td>
    <td>
      <%= @member.address %>
    </td>
  </tr>
</table>
<hr>
<% if @member.number_of_games.zero? %>
  <table>
    <tr>
      <td>
        <strong><%= @member.full_name %> game count : </strong>
      </td>
      <td>
        0
      </td>
    </tr>
  </table>
<% else %>
  <table>
    <tr>
      <td>
        <strong><%= @member.full_name %> game count: </strong>
      </td>
      <td>
        <%= @member.number_of_games %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Number of wins : </strong>
      </td>
      <td>
        <%= win_games_count(@member.participants) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Number of losses : </strong>
      </td>
      <td>
        <%= los_games_count(@member.participants) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Average score : </strong>
      </td>
      <td>
        <%= avrage_score(@member.participants) %>
      </td>
    </tr>
  </table>
  <hr>

  <table>
    <tr>
      <td>
        <strong>Highest Score : </strong>
      </td>
      <td>
        <%= @rank_details[:highest_score] %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Game Name : </strong>
      </td>
      <td>
        <%= @rank_details[:game_name] %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Game Date : </strong>
      </td>
      <td>
        <%= @rank_details[:game_time] %>
      </td>
    </tr>
    <tr>
      <td>
        <strong><%= @member.full_name %> Game Against : </strong>
      </td>
      <td>
        <%= @rank_details[:another_player] %>
      </td>
    </tr>
  </table>

<% end %>